global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

scrape_configs:
  - job_name: 'hive-mind-primary'
    static_configs:
      - targets: ['hive-mind-primary:9090']
    scrape_interval: 10s
    metrics_path: /metrics
    
  - job_name: 'hive-mind-secondary-1'
    static_configs:
      - targets: ['hive-mind-secondary-1:9090']
    scrape_interval: 10s
    metrics_path: /metrics
    
  - job_name: 'hive-mind-secondary-2'
    static_configs:
      - targets: ['hive-mind-secondary-2:9090']
    scrape_interval: 10s
    metrics_path: /metrics

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093